#!/usr/bin/perl

use strict;
use warnings;
use File::Basename;

$| = 1;

print("HTTP/1.0 200 OK\n");
print("Content-Type: text/html; charset=UTF-8\n\n");

open HEADER, "< ./HEADER";
print <HEADER>;
close HEADER;

my $qs = $ENV{'QUERY_STRING'};

if (!defined($qs)) {
  system('top -1 -b -n 1 | head -n 8 | xargs -I XXX echo XXX "<br />"');
  print("</section><section>\n");
  print("MPD 1 - ");
  system('/usr/local/bin/mpc -p 6600 status');
  print("</section><section>\n");
  print("MPD 2 - ");
  system('/usr/local/bin/mpc -p 6602 status');
  print("</section><section>\n");
  print("SBAgen - ");
  system('ps ax | grep sbagen | grep -v grep | tail -c +28');
  print("</section><section>\n");
  print("KeepAlive - ");
  system('ps ax | grep speaker-test | grep -v grep | tail -c +28');
  print("</section><section>\n");
  print('<header><a href="/">Back</a></header>' . "\n");
} else {

}

open FOOTER, "< ./FOOTER";
print <FOOTER>;
close FOOTER;
