#!/usr/bin/perl

use strict;
use warnings;

$| = 1;

system('/usr/local/bin/mpc -P xxx clear > /dev/null 2> /dev/null &');
system('/usr/local/bin/mpdrandom -l --password xxx > /dev/null 2> /dev/null &');
print("HTTP/1.1 200 OK\n");
print("Location: /\n\n");
