#!/usr/bin/perl

use strict;
use warnings;

open HEADER, "< ../config/soundscapes";
my $dir = <HEADER>;
close HEADER;

system('play -q -v 0.96 "' . $dir . '" > /dev/null 2> /dev/null &');
print("HTTP/1.1 200 OK\n");
print("Location: /\n\n");
