#!/usr/bin/perl

use strict;
use warnings;

# echo Playing rain with thunderstorm
system('play -q -v 0.96 /media/soundscapes/*Thunder* > /dev/null 2> /dev/null &');
print("HTTP/1.1 200 OK\n");
print("Location: /\n\n");
