#!/usr/bin/perl

use strict;
use warnings;

open HEADER, "< ../config/sba";
my $dir = <HEADER>;
close HEADER;

system('sbagen -d sba "' . $dir . '" > /dev/null 2> /dev/null &');
print("HTTP/1.1 200 OK\n");
print("Location: /\n\n");
